import 'package:flutter/material.dart';

class LanguageOption {
  final String code;
  final String name;
  final String nativeName;

  const LanguageOption({
    required this.code,
    required this.name,
    required this.nativeName,
  });

  Locale get locale => Locale(code);
}

class AppLocalizations {
  final Locale locale;

  const AppLocalizations(this.locale);

  static const LocalizationsDelegate<AppLocalizations> delegate =
      AppLocalizationsDelegate();

  static const List<Locale> supportedLocales = [
    Locale('en'),
    Locale('zh'),
    Locale('es'),
    Locale('fr'),
    Locale('ar'),
    Locale('hi'),
    Locale('bn'),
    Locale('ru'),
    Locale('tr'),
    Locale('id'),
  ];

  static const List<LanguageOption> languages = [
    LanguageOption(
      code: 'en',
      name: 'English',
      nativeName: 'English',
    ),
    LanguageOption(
      code: 'zh',
      name: 'Chinese',
      nativeName: '中文',
    ),
    LanguageOption(
      code: 'es',
      name: 'Spanish',
      nativeName: 'Español',
    ),
    LanguageOption(
      code: 'fr',
      name: 'French',
      nativeName: 'Français',
    ),
    LanguageOption(
      code: 'ar',
      name: 'Arabic',
      nativeName: 'العربية',
    ),
    LanguageOption(
      code: 'hi',
      name: 'Hindi',
      nativeName: 'हिन्दी',
    ),
    LanguageOption(
      code: 'bn',
      name: 'Bengali',
      nativeName: 'বাংলা',
    ),
    LanguageOption(
      code: 'ru',
      name: 'Russian',
      nativeName: 'Русский',
    ),
    LanguageOption(
      code: 'tr',
      name: 'Turkish',
      nativeName: 'Türkçe',
    ),
    LanguageOption(
      code: 'id',
      name: 'Indonesian',
      nativeName: 'Bahasa Indonesia',
    ),
  ];

  static const Map<String, Map<String, String>> _translations = {
    'en': {
      'appName': 'POWER FAN',
      'brandName': 'POWER FAN',
      'mineFan': 'Mine FAN',
      'powerFanNetwork': 'POWER FAN NETWORK',
      'fan': 'FAN',
      'afam': 'AFAM',

      'language': 'Language',
      'selectLanguage': 'Select Language',
      'chooseLanguage': 'Choose your language',
      'languageChanged': 'Language changed successfully',

      'login': 'Login',
      'register': 'Register',
      'signIn': 'Sign In',
      'signUp': 'Sign Up',
      'welcomeBack': 'Welcome Back',
      'createAccount': 'Create Account',
      'loginToContinue': 'Login to continue',
      'joinPowerFanNetwork': 'Join POWER FAN NETWORK',

      'username': 'Username',
      'email': 'Email',
      'password': 'Password',
      'confirmPassword': 'Confirm Password',
      'referralCode': 'Referral Code',
      'referralCodeOptional': 'Referral Code (Optional)',
      'enterUsername': 'Enter username',
      'enterEmail': 'Enter email',
      'enterPassword': 'Enter password',
      'enterReferralCode': 'Enter referral code',
      'forgotPassword': 'Forgot Password?',
      'resetPassword': 'Reset Password',

      'home': 'Home',
      'referral': 'Referral',
      'wallet': 'Wallet',
      'settings': 'Settings',

      'balance': 'Balance',
      'fanBalance': 'FAN Balance',
      'afamBalance': 'AFAM Balance',
      'miningBalance': 'Mining Balance',

      'mining': 'Mining',
      'startMining': 'START MINING',
      'miningNow': 'MINING',
      'miningStopped': 'Mining Stopped',
      'claimMining': 'CLAIM MINING',
      'claim': 'Claim',
      'claimed': 'Claimed',
      'miningRate': 'Mining Rate',
      'fanPerHour': 'FAN / Hour',
      'remainingTime': 'Remaining Time',
      'miningSession': 'Mining Session',

      'boostMining': 'Boost Mining',
      'boost': 'Boost',
      'watchAd': 'WATCH AD',
      'adsWatched': 'Ads Watched',
      'dailyAds': 'Daily Ads',
      'maxAds': 'Maximum Ads',
      'boostPerAd': '+0.1 FAN/H per ad',
      'maximumBoost': 'Maximum Boost: +0.7 FAN/H',

      'dailySocialTask': 'Daily Social Task',
      'socialTasks': 'Social Tasks',
      'dailyTasks': 'Daily Tasks',
      'completeTask': 'Complete Task',
      'openTask': 'OPEN TASK',
      'verifyTask': 'VERIFY TASK',
      'claimReward': 'CLAIM REWARD',
      'taskCompleted': 'Task Completed',
      'taskClaimed': 'Reward Already Claimed',
      'taskNotReady': 'Complete the required actions first',

      'follow': 'Follow',
      'comment': 'Comment',
      'share': 'Share',

      'facebook': 'Facebook',
      'instagram': 'Instagram',
      'telegram': 'Telegram',
      'tiktok': 'TikTok',
      'twitterX': 'X',
      'youtube': 'YouTube',

      'referrals': 'Referrals',
      'inviteFriends': 'Invite Friends',
      'inviteAndEarn': 'Invite & Earn',
      'myReferralCode': 'My Referral Code',
      'copyCode': 'COPY CODE',
      'shareCode': 'SHARE CODE',
      'copied': 'Copied',
      'totalReferrals': 'Total Referrals',
      'activeReferrals': 'Active Referrals',
      'referralEarnings': 'Referral Earnings',
      'referralReward': 'Referral Reward',
      'newUserReward': 'New user receives 20 FAN',
      'miningBonus': 'Mining Bonus',
      'perActiveReferral': '+0.02 FAN/H per active referral',

      'afamWallet': 'AFAM Wallet',
      'fanMiningBalance': 'FAN Mining Balance',
      'migration': 'Migration',
      'migrate': 'MIGRATE',
      'migrationComingSoon': 'Migration Coming Soon',
      'migrationInfo':
          'Your FAN balance can be migrated to AFAM later.',
      'migrationRate': 'Migration Rate',
      'oneHundredFanOneAfam': '100 FAN = 1 AFAM',
      'transactions': 'Transactions',
      'noTransactions': 'No transactions yet',
      'send': 'SEND',
      'receive': 'RECEIVE',

      'kyc': 'KYC',
      'kycVerification': 'KYC Verification',
      'faceVerification': 'Face Verification',
      'faceVerificationComingSoon':
          'Face Verification Coming Soon',
      'kycComingSoon': 'KYC Coming Soon',
      'kycRequirements': 'KYC Requirements',
      'kycRequirementOne':
          'Complete daily check-in for 30 consecutive days.',
      'kycRequirementTwo':
          'Complete at least one boost every day for 30 days.',
      'kycRequirementThree':
          'Then complete face verification.',
      'startFaceVerification':
          'START FACE VERIFICATION',
      'verificationInProgress':
          'Verification in Progress',
      'verificationComplete':
          'Verification Complete',
      'keepFaceVisible':
          'Keep your face visible in the camera.',
      'lookAtCamera':
          'Look directly at the camera.',
      'verificationSeconds':
          '30-second verification',
      'secondsRemaining':
          'seconds remaining',
      'cameraPermissionRequired':
          'Camera Permission Required',

      'profile': 'Profile',
      'notifications': 'Notifications',
      'security': 'Security',
      'privacy': 'Privacy',
      'about': 'About',
      'help': 'Help',
      'logout': 'Logout',
      'logoutConfirm':
          'Are you sure you want to logout?',

      'save': 'Save',
      'cancel': 'Cancel',
      'close': 'Close',
      'continue': 'Continue',
      'done': 'Done',
      'refresh': 'Refresh',
      'retry': 'Retry',

      'loading': 'Loading...',
      'error': 'Error',
      'success': 'Success',
      'failed': 'Failed',
      'comingSoon': 'Coming Soon',

      'loginRequired': 'Please login first.',
      'invalidEmail':
          'Enter a valid email address.',
      'invalidPassword':
          'Password must be at least 6 characters.',
      'invalidUsername':
          'Enter a valid username.',
      'passwordsDoNotMatch':
          'Passwords do not match.',
      'somethingWentWrong':
          'Something went wrong.',
      'networkError':
          'Network error. Please try again.',
      'noInternet':
          'No internet connection.',
      'operationSuccessful':
          'Operation successful.',

      'dailyBoostRequired':
          'Daily boost required',
      'robotWarning':
          'Robots or automated activity are not allowed.',
      'deviceAlreadyRegistered':
          'This device is already linked to another account.',
      'oneDeviceRuleMessage':
          'One person can use one account on one device. '
          'Multiple accounts on the same device are not allowed.',
      'boostCompleted':
          'Boost completed successfully.',
      'dailyBoostCompleted':
          "Today's boost is completed.",

      'mining_loading': 'MINING',
      'mining_active': 'MINING',
      'session_time': 'Session Time',
      'boost_by_watching_ads':
          'Boost by watching ads',
      'daily_task': 'Daily Task',
      'complete_social_tasks':
          'Complete social tasks',
      'no_daily_tasks':
          'No daily tasks available.',
      'rewarded_ad_not_connected':
          'Rewarded ads are not connected yet.',
    },

    'zh': {
      'appName': 'POWER FAN',
      'brandName': 'POWER FAN',
      'mineFan': '挖掘 FAN',
      'powerFanNetwork': 'POWER FAN NETWORK',
      'fan': 'FAN',
      'afam': 'AFAM',
      'language': '语言',
      'selectLanguage': '选择语言',
      'chooseLanguage': '选择您的语言',
      'languageChanged': '语言更改成功',
      'login': '登录',
      'register': '注册',
      'signIn': '登录',
      'signUp': '注册',
      'welcomeBack': '欢迎回来',
      'createAccount': '创建账户',
      'loginToContinue': '登录后继续',
      'joinPowerFanNetwork': '加入 POWER FAN NETWORK',
      'username': '用户名',
      'email': '电子邮件',
      'password': '密码',
      'confirmPassword': '确认密码',
      'referralCode': '推荐码',
      'forgotPassword': '忘记密码？',
      'home': '首页',
      'referral': '推荐',
      'wallet': '钱包',
      'settings': '设置',
      'balance': '余额',
      'fanBalance': 'FAN 余额',
      'afamBalance': 'AFAM 余额',
      'miningBalance': '挖矿余额',
      'mining': '挖矿',
      'startMining': '开始挖矿',
      'miningNow': '正在挖矿',
      'claimMining': '领取挖矿奖励',
      'miningRate': '挖矿速度',
      'remainingTime': '剩余时间',
      'miningSession': '挖矿会话',
      'boostMining': '加速挖矿',
      'watchAd': '观看广告',
      'adsWatched': '已观看广告',
      'dailySocialTask': '每日社交任务',
      'socialTasks': '社交任务',
      'dailyTasks': '每日任务',
      'completeTask': '完成任务',
      'openTask': '打开任务',
      'verifyTask': '验证任务',
      'claimReward': '领取奖励',
      'taskCompleted': '任务已完成',
      'taskClaimed': '奖励已领取',
      'taskNotReady': '请先完成所需操作',
      'referrals': '推荐人数',
      'inviteFriends': '邀请朋友',
      'referralReward': '推荐奖励',
      'newUserReward': '新用户获得 20 FAN',
      'kyc': 'KYC',
      'kycVerification': 'KYC 验证',
      'faceVerification': '人脸验证',
      'kycComingSoon': 'KYC 即将推出',
      'profile': '个人资料',
      'security': '安全',
      'about': '关于',
      'help': '帮助',
      'logout': '退出登录',
      'save': '保存',
      'cancel': '取消',
      'close': '关闭',
      'loading': '加载中...',
      'error': '错误',
      'success': '成功',
      'comingSoon': '即将推出',
    },

    'es': {
      'appName': 'POWER FAN',
      'brandName': 'POWER FAN',
      'mineFan': 'Minar FAN',
      'powerFanNetwork': 'POWER FAN NETWORK',
      'fan': 'FAN',
      'afam': 'AFAM',
      'language': 'Idioma',
      'selectLanguage': 'Seleccionar idioma',
      'chooseLanguage': 'Elige tu idioma',
      'languageChanged': 'Idioma cambiado correctamente',
      'login': 'Iniciar sesión',
      'register': 'Registrarse',
      'signIn': 'Iniciar sesión',
      'signUp': 'Registrarse',
      'welcomeBack': 'Bienvenido de nuevo',
      'createAccount': 'Crear cuenta',
      'username': 'Nombre de usuario',
      'email': 'Correo electrónico',
      'password': 'Contraseña',
      'home': 'Inicio',
      'referral': 'Referidos',
      'wallet': 'Billetera',
      'settings': 'Configuración',
      'balance': 'Saldo',
      'fanBalance': 'Saldo FAN',
      'afamBalance': 'Saldo AFAM',
      'mining': 'Minería',
      'startMining': 'INICIAR MINERÍA',
      'miningNow': 'MINANDO',
      'claimMining': 'RECLAMAR MINERÍA',
      'miningRate': 'Tasa de minería',
      'remainingTime': 'Tiempo restante',
      'boostMining': 'Acelerar minería',
      'watchAd': 'VER ANUNCIO',
      'dailySocialTask': 'Tarea social diaria',
      'socialTasks': 'Tareas sociales',
      'dailyTasks': 'Tareas diarias',
      'completeTask': 'Completar tarea',
      'openTask': 'ABRIR TAREA',
      'verifyTask': 'VERIFICAR TAREA',
      'claimReward': 'RECLAMAR RECOMPENSA',
      'taskCompleted': 'Tarea completada',
      'taskClaimed': 'Recompensa ya reclamada',
      'referrals': 'Referidos',
      'inviteFriends': 'Invitar amigos',
      'referralReward': 'Recompensa por referido',
      'newUserReward': 'El nuevo usuario recibe 20 FAN',
      'kyc': 'KYC',
      'kycVerification': 'Verificación KYC',
      'faceVerification': 'Verificación facial',
      'kycComingSoon': 'KYC próximamente',
      'profile': 'Perfil',
      'security': 'Seguridad',
      'about': 'Acerca de',
      'help': 'Ayuda',
      'logout': 'Cerrar sesión',
      'save': 'Guardar',
      'cancel': 'Cancelar',
      'close': 'Cerrar',
      'loading': 'Cargando...',
      'error': 'Error',
      'success': 'Éxito',
      'comingSoon': 'Próximamente',
    },

    'fr': {
      'appName': 'POWER FAN',
      'brandName': 'POWER FAN',
      'mineFan': 'Miner du FAN',
      'powerFanNetwork': 'POWER FAN NETWORK',
      'fan': 'FAN',
      'afam': 'AFAM',
      'language': 'Langue',
      'selectLanguage': 'Sélectionner la langue',
      'chooseLanguage': 'Choisissez votre langue',
      'languageChanged': 'Langue modifiée avec succès',
      'login': 'Connexion',
      'register': 'S’inscrire',
      'signIn': 'Se connecter',
      'signUp': 'Créer un compte',
      'welcomeBack': 'Bon retour',
      'createAccount': 'Créer un compte',
      'username': 'Nom d’utilisateur',
      'email': 'E-mail',
      'password': 'Mot de passe',
      'home': 'Accueil',
      'referral': 'Parrainage',
      'wallet': 'Portefeuille',
      'settings': 'Paramètres',
      'balance': 'Solde',
      'fanBalance': 'Solde FAN',
      'afamBalance': 'Solde AFAM',
      'mining': 'Minage',
      'startMining': 'DÉMARRER LE MINAGE',
      'miningNow': 'MINAGE EN COURS',
      'claimMining': 'RÉCLAMER LE MINAGE',
      'miningRate': 'Taux de minage',
      'remainingTime': 'Temps restant',
      'boostMining': 'Accélérer le minage',
      'watchAd': 'REGARDER LA PUBLICITÉ',
      'dailySocialTask': 'Tâche sociale quotidienne',
      'socialTasks': 'Tâches sociales',
      'dailyTasks': 'Tâches quotidiennes',
      'completeTask': 'Terminer la tâche',
      'openTask': 'OUVRIR LA TÂCHE',
      'verifyTask': 'VÉRIFIER LA TÂCHE',
      'claimReward': 'RÉCLAMER LA RÉCOMPENSE',
      'taskCompleted': 'Tâche terminée',
      'taskClaimed': 'Récompense déjà réclamée',
      'referrals': 'Parrainages',
      'inviteFriends': 'Inviter des amis',
      'referralReward': 'Récompense de parrainage',
      'newUserReward': 'Le nouvel utilisateur reçoit 20 FAN',
      'kyc': 'KYC',
      'kycVerification': 'Vérification KYC',
      'faceVerification': 'Vérification faciale',
      'kycComingSoon': 'KYC bientôt disponible',
      'profile': 'Profil',
      'security': 'Sécurité',
      'about': 'À propos',
      'help': 'Aide',
      'logout': 'Déconnexion',
      'save': 'Enregistrer',
      'cancel': 'Annuler',
      'close': 'Fermer',
      'loading': 'Chargement...',
      'error': 'Erreur',
      'success': 'Succès',
      'comingSoon': 'Bientôt disponible',
    },

    'ar': {
      'appName': 'POWER FAN',
      'brandName': 'POWER FAN',
      'mineFan': 'تعدين FAN',
      'powerFanNetwork': 'POWER FAN NETWORK',
      'fan': 'FAN',
      'afam': 'AFAM',
      'language': 'اللغة',
      'selectLanguage': 'اختر اللغة',
      'chooseLanguage': 'اختر لغتك',
      'languageChanged': 'تم تغيير اللغة بنجاح',
      'login': 'تسجيل الدخول',
      'register': 'تسجيل',
      'signIn': 'تسجيل الدخول',
      'signUp': 'إنشاء حساب',
      'welcomeBack': 'مرحباً بعودتك',
      'createAccount': 'إنشاء حساب',
      'username': 'اسم المستخدم',
      'email': 'البريد الإلكتروني',
      'password': 'كلمة المرور',
      'home': 'الرئيسية',
      'referral': 'الإحالة',
      'wallet': 'المحفظة',
      'settings': 'الإعدادات',
      'balance': 'الرصيد',
      'fanBalance': 'رصيد FAN',
      'afamBalance': 'رصيد AFAM',
      'mining': 'التعدين',
      'startMining': 'بدء التعدين',
      'miningNow': 'التعدين جارٍ',
      'claimMining': 'استلام مكافأة التعدين',
      'miningRate': 'معدل التعدين',
      'remainingTime': 'الوقت المتبقي',
      'boostMining': 'تسريع التعدين',
      'watchAd': 'شاهد الإعلان',
      'dailySocialTask': 'المهمة الاجتماعية اليومية',
      'socialTasks': 'المهام الاجتماعية',
      'dailyTasks': 'المهام اليومية',
      'completeTask': 'أكمل المهمة',
      'openTask': 'فتح المهمة',
      'verifyTask': 'تحقق من المهمة',
      'claimReward': 'استلام المكافأة',
      'taskCompleted': 'اكتملت المهمة',
      'taskClaimed': 'تم استلام المكافأة',
      'referrals': 'الإحالات',
      'inviteFriends': 'دعوة الأصدقاء',
      'referralReward': 'مكافأة الإحالة',
      'newUserReward': 'يحصل المستخدم الجديد على 20 FAN',
      'kyc': 'KYC',
      'kycVerification': 'تحقق KYC',
      'faceVerification': 'التحقق من الوجه',
      'kycComingSoon': 'KYC قريباً',
      'profile': 'الملف الشخصي',
      'security': 'الأمان',
      'about': 'حول التطبيق',
      'help': 'المساعدة',
      'logout': 'تسجيل الخروج',
      'save': 'حفظ',
      'cancel': 'إلغاء',
      'close': 'إغلاق',
      'loading': 'جارٍ التحميل...',
      'error': 'خطأ',
      'success': 'نجاح',
      'comingSoon': 'قريباً',
    },
    'hi': {
      'appName': 'POWER FAN',
      'brandName': 'POWER FAN',
      'mineFan': 'FAN माइन करें',
      'powerFanNetwork': 'POWER FAN NETWORK',
      'fan': 'FAN',
      'afam': 'AFAM',
      'language': 'भाषा',
      'selectLanguage': 'भाषा चुनें',
      'chooseLanguage': 'अपनी भाषा चुनें',
      'languageChanged': 'भाषा सफलतापूर्वक बदल गई',
      'login': 'लॉगिन',
      'register': 'रजिस्टर',
      'signIn': 'साइन इन',
      'signUp': 'साइन अप',
      'welcomeBack': 'वापसी पर स्वागत है',
      'createAccount': 'खाता बनाएं',
      'username': 'यूज़रनेम',
      'email': 'ईमेल',
      'password': 'पासवर्ड',
      'home': 'होम',
      'referral': 'रेफरल',
      'wallet': 'वॉलेट',
      'settings': 'सेटिंग्स',
      'balance': 'बैलेंस',
      'fanBalance': 'FAN बैलेंस',
      'afamBalance': 'AFAM बैलेंस',
      'mining': 'माइनिंग',
      'startMining': 'माइनिंग शुरू करें',
      'miningNow': 'माइनिंग चल रही है',
      'claimMining': 'माइनिंग रिवॉर्ड लें',
      'miningRate': 'माइनिंग रेट',
      'remainingTime': 'बाकी समय',
      'boostMining': 'माइनिंग बढ़ाएं',
      'watchAd': 'विज्ञापन देखें',
      'dailySocialTask': 'दैनिक सोशल टास्क',
      'socialTasks': 'सोशल टास्क',
      'dailyTasks': 'दैनिक टास्क',
      'completeTask': 'टास्क पूरा करें',
      'openTask': 'टास्क खोलें',
      'verifyTask': 'टास्क सत्यापित करें',
      'claimReward': 'रिवार्ड लें',
      'taskCompleted': 'टास्क पूरा हुआ',
      'taskClaimed': 'रिवार्ड लिया जा चुका है',
      'referrals': 'रेफरल',
      'inviteFriends': 'दोस्तों को आमंत्रित करें',
      'referralReward': 'रेफरल रिवार्ड',
      'newUserReward': 'नए यूज़र को 20 FAN',
      'kyc': 'KYC',
      'kycVerification': 'KYC सत्यापन',
      'faceVerification': 'फेस वेरिफिकेशन',
      'kycComingSoon': 'KYC जल्द आ रहा है',
      'profile': 'प्रोफ़ाइल',
      'security': 'सुरक्षा',
      'about': 'अबाउट',
      'help': 'मदद',
      'logout': 'लॉगआउट',
      'save': 'सेव',
      'cancel': 'रद्द करें',
      'close': 'बंद करें',
      'loading': 'लोड हो रहा है...',
      'error': 'त्रुटि',
      'success': 'सफल',
      'comingSoon': 'जल्द आ रहा है',
    },

    'bn': {
      'appName': 'POWER FAN',
      'brandName': 'POWER FAN',
      'mineFan': 'FAN মাইন করুন',
      'powerFanNetwork': 'POWER FAN NETWORK',
      'fan': 'FAN',
      'afam': 'AFAM',
      'language': 'ভাষা',
      'selectLanguage': 'ভাষা নির্বাচন করুন',
      'chooseLanguage': 'আপনার ভাষা নির্বাচন করুন',
      'languageChanged': 'ভাষা সফলভাবে পরিবর্তন হয়েছে',
      'login': 'লগইন',
      'register': 'রেজিস্টার',
      'signIn': 'সাইন ইন',
      'signUp': 'সাইন আপ',
      'welcomeBack': 'আবার স্বাগতম',
      'createAccount': 'অ্যাকাউন্ট তৈরি করুন',
      'username': 'ইউজারনেম',
      'email': 'ইমেইল',
      'password': 'পাসওয়ার্ড',
      'home': 'হোম',
      'referral': 'রেফারেল',
      'wallet': 'ওয়ালেট',
      'settings': 'সেটিংস',
      'balance': 'ব্যালেন্স',
      'fanBalance': 'FAN ব্যালেন্স',
      'afamBalance': 'AFAM ব্যালেন্স',
      'mining': 'মাইনিং',
      'startMining': 'মাইনিং শুরু করুন',
      'miningNow': 'মাইনিং চলছে',
      'claimMining': 'মাইনিং রিওয়ার্ড নিন',
      'miningRate': 'মাইনিং রেট',
      'remainingTime': 'বাকি সময়',
      'boostMining': 'মাইনিং বুস্ট',
      'watchAd': 'বিজ্ঞাপন দেখুন',
      'dailySocialTask': 'দৈনিক সোশ্যাল টাস্ক',
      'socialTasks': 'সোশ্যাল টাস্ক',
      'dailyTasks': 'দৈনিক টাস্ক',
      'completeTask': 'টাস্ক সম্পন্ন করুন',
      'openTask': 'টাস্ক খুলুন',
      'verifyTask': 'টাস্ক যাচাই করুন',
      'claimReward': 'রিওয়ার্ড নিন',
      'taskCompleted': 'টাস্ক সম্পন্ন হয়েছে',
      'taskClaimed': 'রিওয়ার্ড নেওয়া হয়েছে',
      'referrals': 'রেফারেল',
      'inviteFriends': 'বন্ধুদের আমন্ত্রণ করুন',
      'referralReward': 'রেফারেল রিওয়ার্ড',
      'newUserReward': 'নতুন ইউজার 20 FAN পাবে',
      'kyc': 'KYC',
      'kycVerification': 'KYC যাচাই',
      'faceVerification': 'ফেস ভেরিফিকেশন',
      'kycComingSoon': 'KYC শীঘ্রই আসছে',
      'profile': 'প্রোফাইল',
      'security': 'নিরাপত্তা',
      'about': 'সম্পর্কে',
      'help': 'সহায়তা',
      'logout': 'লগআউট',
      'save': 'সংরক্ষণ',
      'cancel': 'বাতিল',
      'close': 'বন্ধ',
      'loading': 'লোড হচ্ছে...',
      'error': 'ত্রুটি',
      'success': 'সফল',
      'comingSoon': 'শীঘ্রই আসছে',
    },

    'ru': {
      'appName': 'POWER FAN',
      'brandName': 'POWER FAN',
      'mineFan': 'Майнинг FAN',
      'powerFanNetwork': 'POWER FAN NETWORK',
      'fan': 'FAN',
      'afam': 'AFAM',
      'language': 'Язык',
      'selectLanguage': 'Выберите язык',
      'chooseLanguage': 'Выберите ваш язык',
      'languageChanged': 'Язык успешно изменён',
      'login': 'Войти',
      'register': 'Регистрация',
      'signIn': 'Войти',
      'signUp': 'Регистрация',
      'welcomeBack': 'С возвращением',
      'createAccount': 'Создать аккаунт',
      'username': 'Имя пользователя',
      'email': 'Электронная почта',
      'password': 'Пароль',
      'home': 'Главная',
      'referral': 'Рефералы',
      'wallet': 'Кошелёк',
      'settings': 'Настройки',
      'balance': 'Баланс',
      'fanBalance': 'Баланс FAN',
      'afamBalance': 'Баланс AFAM',
      'mining': 'Майнинг',
      'startMining': 'НАЧАТЬ МАЙНИНГ',
      'miningNow': 'МАЙНИНГ',
      'claimMining': 'ПОЛУЧИТЬ НАГРАДУ',
      'miningRate': 'Скорость майнинга',
      'remainingTime': 'Оставшееся время',
      'boostMining': 'Ускорить майнинг',
      'watchAd': 'СМОТРЕТЬ РЕКЛАМУ',
      'dailySocialTask': 'Ежедневное социальное задание',
      'socialTasks': 'Социальные задания',
      'dailyTasks': 'Ежедневные задания',
      'completeTask': 'Выполнить задание',
      'openTask': 'ОТКРЫТЬ',
      'verifyTask': 'ПРОВЕРИТЬ',
      'claimReward': 'ПОЛУЧИТЬ НАГРАДУ',
      'taskCompleted': 'Задание выполнено',
      'taskClaimed': 'Награда уже получена',
      'referrals': 'Рефералы',
      'inviteFriends': 'Пригласить друзей',
      'referralReward': 'Реферальная награда',
      'newUserReward': 'Новый пользователь получает 20 FAN',
      'kyc': 'KYC',
      'kycVerification': 'Проверка KYC',
      'faceVerification': 'Проверка лица',
      'kycComingSoon': 'KYC скоро будет доступен',
      'profile': 'Профиль',
      'security': 'Безопасность',
      'about': 'О приложении',
      'help': 'Помощь',
      'logout': 'Выйти',
      'save': 'Сохранить',
      'cancel': 'Отмена',
      'close': 'Закрыть',
      'loading': 'Загрузка...',
      'error': 'Ошибка',
      'success': 'Успешно',
      'comingSoon': 'Скоро',
    },

    'tr': {
      'appName': 'POWER FAN',
      'brandName': 'POWER FAN',
      'mineFan': 'FAN Madenciliği',
      'powerFanNetwork': 'POWER FAN NETWORK',
      'fan': 'FAN',
      'afam': 'AFAM',
      'language': 'Dil',
      'selectLanguage': 'Dil Seç',
      'chooseLanguage': 'Dilinizi seçin',
      'languageChanged': 'Dil başarıyla değiştirildi',
      'login': 'Giriş',
      'register': 'Kayıt Ol',
      'signIn': 'Giriş Yap',
      'signUp': 'Kayıt Ol',
      'welcomeBack': 'Tekrar Hoş Geldiniz',
      'createAccount': 'Hesap Oluştur',
      'username': 'Kullanıcı adı',
      'email': 'E-posta',
      'password': 'Şifre',
      'home': 'Ana Sayfa',
      'referral': 'Referans',
      'wallet': 'Cüzdan',
      'settings': 'Ayarlar',
      'balance': 'Bakiye',
      'fanBalance': 'FAN Bakiyesi',
      'afamBalance': 'AFAM Bakiyesi',
      'mining': 'Madencilik',
      'startMining': 'MADENCİLİĞİ BAŞLAT',
      'miningNow': 'MADENCİLİK',
      'claimMining': 'ÖDÜLÜ AL',
      'miningRate': 'Madencilik Hızı',
      'remainingTime': 'Kalan Süre',
      'boostMining': 'Madenciliği Hızlandır',
      'watchAd': 'REKLAM İZLE',
      'dailySocialTask': 'Günlük Sosyal Görev',
      'socialTasks': 'Sosyal Görevler',
      'dailyTasks': 'Günlük Görevler',
      'completeTask': 'Görevi Tamamla',
      'openTask': 'GÖREVİ AÇ',
      'verifyTask': 'GÖREVİ DOĞRULA',
      'claimReward': 'ÖDÜLÜ AL',
      'taskCompleted': 'Görev Tamamlandı',
      'taskClaimed': 'Ödül Zaten Alındı',
      'referrals': 'Referanslar',
      'inviteFriends': 'Arkadaşlarını Davet Et',
      'referralReward': 'Referans Ödülü',
      'newUserReward': 'Yeni kullanıcı 20 FAN alır',
      'kyc': 'KYC',
      'kycVerification': 'KYC Doğrulaması',
      'faceVerification': 'Yüz Doğrulama',
      'kycComingSoon': 'KYC Yakında',
      'profile': 'Profil',
      'security': 'Güvenlik',
      'about': 'Hakkında',
      'help': 'Yardım',
      'logout': 'Çıkış Yap',
      'save': 'Kaydet',
      'cancel': 'İptal',
      'close': 'Kapat',
      'loading': 'Yükleniyor...',
      'error': 'Hata',
      'success': 'Başarılı',
      'comingSoon': 'Yakında',
    },

    'id': {
      'appName': 'POWER FAN',
      'brandName': 'POWER FAN',
      'mineFan': 'Mining FAN',
      'powerFanNetwork': 'POWER FAN NETWORK',
      'fan': 'FAN',
      'afam': 'AFAM',
      'language': 'Bahasa',
      'selectLanguage': 'Pilih Bahasa',
      'chooseLanguage': 'Pilih bahasa Anda',
      'languageChanged': 'Bahasa berhasil diubah',
      'login': 'Masuk',
      'register': 'Daftar',
      'signIn': 'Masuk',
      'signUp': 'Daftar',
      'welcomeBack': 'Selamat Datang Kembali',
      'createAccount': 'Buat Akun',
      'username': 'Nama Pengguna',
      'email': 'Email',
      'password': 'Kata Sandi',
      'home': 'Beranda',
      'referral': 'Referral',
      'wallet': 'Dompet',
      'settings': 'Pengaturan',
      'balance': 'Saldo',
      'fanBalance': 'Saldo FAN',
      'afamBalance': 'Saldo AFAM',
      'mining': 'Mining',
      'startMining': 'MULAI MINING',
      'miningNow': 'MINING',
      'claimMining': 'KLAIM HADIAH',
      'miningRate': 'Kecepatan Mining',
      'remainingTime': 'Waktu Tersisa',
      'boostMining': 'Boost Mining',
      'watchAd': 'TONTON IKLAN',
      'dailySocialTask': 'Tugas Sosial Harian',
      'socialTasks': 'Tugas Sosial',
      'dailyTasks': 'Tugas Harian',
      'completeTask': 'Selesaikan Tugas',
      'openTask': 'BUKA TUGAS',
      'verifyTask': 'VERIFIKASI',
      'claimReward': 'KLAIM HADIAH',
      'taskCompleted': 'Tugas Selesai',
      'taskClaimed': 'Hadiah Sudah Diklaim',
      'referrals': 'Referral',
      'inviteFriends': 'Undang Teman',
      'referralReward': 'Hadiah Referral',
      'newUserReward': 'Pengguna baru mendapat 20 FAN',
      'kyc': 'KYC',
      'kycVerification': 'Verifikasi KYC',
      'faceVerification': 'Verifikasi Wajah',
      'kycComingSoon': 'KYC Segera Hadir',
      'profile': 'Profil',
      'security': 'Keamanan',
      'about': 'Tentang',
      'help': 'Bantuan',
      'logout': 'Keluar',
      'save': 'Simpan',
      'cancel': 'Batal',
      'close': 'Tutup',
      'loading': 'Memuat...',
      'error': 'Kesalahan',
      'success': 'Berhasil',
      'comingSoon': 'Segera Hadir',
    },
  };

  static const Map<String, String> _legacyKeyAliases = {
    'mining_loading': 'mining_loading',
    'mining_active': 'mining_active',
    'mining_rate': 'miningRate',
    'session_time': 'session_time',
    'boost_by_watching_ads': 'boostMining',
    'watch_ad': 'watchAd',
    'daily_task': 'dailySocialTask',
    'complete_social_tasks': 'completeTask',
    'no_daily_tasks': 'no_daily_tasks',
    'rewarded_ad_not_connected':
        'rewarded_ad_not_connected',
    'claim_mining': 'claimMining',
    'start_mining': 'startMining',
    'fan_balance': 'fanBalance',
    'afam_balance': 'afamBalance',
    'mining_balance': 'miningBalance',
    'remaining_time': 'remainingTime',
    'mining_session': 'miningSession',
    'ads_watched': 'adsWatched',
    'daily_ads': 'dailyAds',
    'max_ads': 'maxAds',
    'boost_mining': 'boostMining',
    'daily_social_task': 'dailySocialTask',
    'complete_task': 'completeTask',
    'open_task': 'openTask',
    'verify_task': 'verifyTask',
    'claim_reward': 'claimReward',
    'task_completed': 'taskCompleted',
    'task_claimed': 'taskClaimed',
    'task_not_ready': 'taskNotReady',
  };

  String translate(String key) {
    final language =
        _translations[locale.languageCode] ??
        _translations['en']!;

    final resolvedKey =
        _legacyKeyAliases[key] ?? key;

    return language[resolvedKey] ??
        _translations['en']![resolvedKey] ??
        language[key] ??
        _translations['en']![key] ??
        key;
  }

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(
          context,
          AppLocalizations,
        ) ??
        const AppLocalizations(Locale('en'));
  }
}

class AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return AppLocalizations.supportedLocales.any(
      (supported) =>
          supported.languageCode ==
          locale.languageCode,
    );
  }

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(
    AppLocalizationsDelegate old) {
    return false;
  }
}
