// lib/localization/app_localizations.dart

import 'package:flutter/material.dart';

class LanguageOption {
  final String code;
  final String name;
  final String nativeName;

  const LanguageOption({
    required this.code,
    required this.name,
    required this.nativeName,
  });

  Locale get locale => Locale(code);
}

class AppLocalizations {
  final Locale locale;

  const AppLocalizations(this.locale);

  static const supportedLocales = [
    Locale('en'),
    Locale('zh'),
    Locale('es'),
    Locale('fr'),
    Locale('ar'),
    Locale('hi'),
    Locale('bn'),
    Locale('ru'),
    Locale('tr'),
    Locale('id'),
  ];

  static const AppLocalizationsDelegate delegate =
      AppLocalizationsDelegate();

  static const List<LanguageOption> languages = [
    LanguageOption(
      code: 'en',
      name: 'English',
      nativeName: 'English',
    ),
    LanguageOption(
      code: 'zh',
      name: 'Chinese',
      nativeName: '中文',
    ),
    LanguageOption(
      code: 'es',
      name: 'Spanish',
      nativeName: 'Español',
    ),
    LanguageOption(
      code: 'fr',
      name: 'French',
      nativeName: 'Français',
    ),
    LanguageOption(
      code: 'ar',
      name: 'Arabic',
      nativeName: 'العربية',
    ),
    LanguageOption(
      code: 'hi',
      name: 'Hindi',
      nativeName: 'हिन्दी',
    ),
    LanguageOption(
      code: 'bn',
      name: 'Bengali',
      nativeName: 'বাংলা',
    ),
    LanguageOption(
      code: 'ru',
      name: 'Russian',
      nativeName: 'Русский',
    ),
    LanguageOption(
      code: 'tr',
      name: 'Turkish',
      nativeName: 'Türkçe',
    ),
    LanguageOption(
      code: 'id',
      name: 'Indonesian',
      nativeName: 'Bahasa Indonesia',
    ),
  ];

  static const Map<String, Map<String, String>> _translations = {
    'en': {
      'appName': 'POWER FAN',
      'brandName': 'POWER FAN',
      'mineFan': 'Mine FAN',
      'powerFanNetwork': 'POWER FAN NETWORK',
      'fan': 'FAN',
      'afam': 'AFAM',
      'language': 'Language',
      'selectLanguage': 'Select Language',
      'chooseLanguage': 'Choose your language',
      'languageChanged': 'Language changed successfully',
      'login': 'Login',
      'register': 'Register',
      'signIn': 'Sign In',
      'signUp': 'Sign Up',
      'welcomeBack': 'Welcome Back',
      'createAccount': 'Create Account',
      'loginToContinue': 'Login to continue',
      'joinPowerFanNetwork': 'Join POWER FAN NETWORK',
      'username': 'Username',
      'email': 'Email',
      'password': 'Password',
      'confirmPassword': 'Confirm Password',
      'referralCode': 'Referral Code',
      'referralCodeOptional': 'Referral Code (Optional)',
      'enterUsername': 'Enter username',
      'enterEmail': 'Enter email',
      'enterPassword': 'Enter password',
      'enterReferralCode': 'Enter referral code',
      'forgotPassword': 'Forgot password?',
      'resetPassword': 'Reset Password',
      'dontHaveAccount': "Don't have an account?",
      'alreadyHaveAccount': 'Already have an account?',
      'passwordHidden': 'Password hidden',
      'passwordVisible': 'Password visible',
      'home': 'Home',
      'balance': 'Balance',
      'fanBalance': 'FAN Balance',
      'afamBalance': 'AFAM Balance',
      'miningBalance': 'Mining Balance',
      'originalCoin': 'Original Coin',
      'mining': 'Mining',
      'startMining': 'START MINING',
      'miningNow': 'MINING',
      'miningStopped': 'Mining Stopped',
      'claimMining': 'CLAIM MINING',
      'claim': 'Claim',
      'claimed': 'Claimed',
      'miningRate': 'Mining Rate',
      'fanPerHour': 'FAN / Hour',
      'remainingTime': 'Remaining Time',
      'miningSession': 'Mining Session',
      'miningEndsIn': 'Mining ends in',
      'miningStarted': 'Mining started successfully',
      'miningCompleted': 'Mining session completed',
      'boostMining': 'Boost Mining',
      'boost': 'Boost',
      'watchAd': 'WATCH AD',
      'adsWatched': 'Ads Watched',
      'dailyAds': 'Daily Ads',
      'maxAds': 'Maximum Ads',
      'boostPerAd': '+0.1 FAN/H per ad',
      'maximumBoost': 'Maximum Boost: +0.7 FAN/H',
      'adReward': 'Ad Reward',
      'rewardedAd': 'Rewarded Ad',
      'watchAdsToBoost':
          'Watch ads to increase your mining rate',
      'adSystemComingSoon': 'Rewarded ad system coming soon',
      'dailySocialTask': 'Daily Social Task',
      'socialTasks': 'Social Tasks',
      'dailyTasks': 'Daily Tasks',
      'noDailyTasks': 'No daily tasks available.',
      'completeTask': 'Complete Task',
      'openTask': 'OPEN TASK',
      'verifyTask': 'VERIFY TASK',
      'claimReward': 'CLAIM REWARD',
      'taskCompleted': 'Task completed',
      'taskClaimed': 'Reward already claimed',
      'taskNotReady':
          'Complete the required actions first',
      'follow': 'Follow',
      'comment': 'Comment',
      'share': 'Share',
      'checkIn': 'Check-in',
      'dailyCheckIn': 'Daily Check-in',
      'socialReward': 'Social Reward',
      'fanReward': 'FAN Reward',
      'facebook': 'Facebook',
      'instagram': 'Instagram',
      'telegram': 'Telegram',
      'tiktok': 'TikTok',
      'twitterX': 'X',
      'youtube': 'YouTube',
      'referral': 'Referral',
      'referrals': 'Referrals',
      'inviteFriends': 'Invite Friends',
      'inviteAndEarn': 'Invite & Earn',
      'myReferralCode': 'My Referral Code',
      'copyCode': 'COPY CODE',
      'shareCode': 'SHARE CODE',
      'copied': 'Copied',
      'totalReferrals': 'Total Referrals',
      'activeReferrals': 'Active Referrals',
      'referralEarnings': 'Referral Earnings',
      'referralReward': 'Referral Reward',
      'newUserReward': 'New user receives 20 FAN',
      'miningBonus': 'Mining Bonus',
      'perActiveReferral':
          '+0.02 FAN/H per active referral',
      'referralHowItWorks': 'How Referral Works',
      'referralStepOne':
          'Share your referral code with friends.',
      'referralStepTwo':
          'Your friend joins using your code.',
      'referralStepThree':
          'You receive 5 FAN and a mining bonus.',
      'wallet': 'Wallet',
      'afamWallet': 'AFAM Wallet',
      'fanMiningBalance': 'FAN Mining Balance',
      'migration': 'Migration',
      'migrate': 'MIGRATE',
      'migrationComingSoon': 'Migration Coming Soon',
      'migrationInfo':
          'Your FAN balance can later be migrated to AFAM.',
      'migrationRate': 'Migration Rate',
      'oneHundredFanOneAfam': '100 FAN = 1 AFAM',
      'transactions': 'Transactions',
      'noTransactions': 'No transactions yet',
      'send': 'SEND',
      'receive': 'RECEIVE',
      'sendAfam': 'Send AFAM',
      'receiveAfam': 'Receive AFAM',
      'usernameTransactions':
          'Transactions are made using usernames.',
      'walletSecurity': 'Wallet Security',
      'walletSecurityMessage':
          'Keep your account secure. Never share your password or verification information.',
      'kyc': 'KYC',
      'kycVerification': 'KYC Verification',
      'faceVerification': 'Face Verification',
      'faceVerificationComingSoon':
          'Face Verification Coming Soon',
      'kycComingSoon': 'KYC Coming Soon',
      'kycRequirements': 'KYC Requirements',
      'kycRequirementOne':
          'Complete daily check-in for 30 consecutive days.',
      'kycRequirementTwo':
          'Complete at least one boost every day for 30 days.',
      'kycRequirementThree':
          'Then complete Face Verification.',
      'thirtyDayCheckIn': '30-Day Daily Check-in',
      'thirtyDayBoost': '30-Day Daily Boost',
      'kycUnlocked': 'KYC Unlocked',
      'kycLocked': 'KYC Locked',
      'startFaceVerification':
          'START FACE VERIFICATION',
      'verificationInProgress':
          'Verification in progress',
      'verificationComplete':
          'Verification complete',
      'keepFaceVisible':
          'Keep your face visible in the camera.',
      'lookAtCamera':
          'Look directly at the camera.',
      'verificationSeconds':
          '30-second verification',
      'secondsRemaining':
          'seconds remaining',
      'cameraPermissionRequired':
          'Camera Permission Required',
      'cameraPermissionMessage':
          'Camera access is required for live face verification.',
      'oneDeviceOneAccount':
          'One Device = One Account',
      'deviceSecurity': 'Device Security',
      'settings': 'Settings',
      'account': 'Account',
      'profile': 'Profile',
      'notifications': 'Notifications',
      'security': 'Security',
      'privacy': 'Privacy',
      'about': 'About',
      'help': 'Help',
      'logout': 'Logout',
      'logoutConfirm':
          'Are you sure you want to logout?',
      'save': 'Save',
      'cancel': 'Cancel',
      'close': 'Close',
      'continue': 'Continue',
      'done': 'Done',
      'refresh': 'Refresh',
      'retry': 'Retry',
      'loading': 'Loading...',
      'error': 'Error',
      'success': 'Success',
      'failed': 'Failed',
      'comingSoon': 'Coming Soon',
      'enabled': 'Enabled',
      'disabled': 'Disabled',
      'yes': 'Yes',
      'no': 'No',
      'today': 'Today',
      'tomorrow': 'Tomorrow',
      'loginRequired': 'Please login first.',
      'invalidEmail':
          'Enter a valid email address.',
      'invalidPassword':
          'Password must be at least 6 characters.',
      'invalidUsername':
          'Enter a valid username.',
      'passwordsDoNotMatch':
          'Passwords do not match.',
      'somethingWentWrong':
          'Something went wrong.',
      'networkError':
          'Network error. Please try again.',
      'noInternet':
          'No internet connection.',
      'operationSuccessful':
          'Operation successful.',
      'claimRequiresAd':
          'Watch the rewarded ad before claiming your 24-hour mining reward.',
      'claimAdMessage':
          'After the ad is completed, your mining reward will be claimed and a new 24-hour session will start automatically.',
      'dailyBoostRequired':
          'Daily boost required',
      'dailyBoostReminder':
          'Watch at least one boost ad every day to stay active and progress toward KYC.',
      'miningRules': 'Mining Rules',
      'miningRuleClaim24h':
          'Claim your mining reward after every 24-hour session.',
      'miningRuleRateIncrease':
          'Mining rate can only increase through approved boosts and active referrals.',
      'miningRuleDailyBoost':
          'Complete at least one boost every day to stay active.',
      'robotWarning':
          'Robot or automated activity is not allowed.',
      'unauthorizedActivity':
          'Unauthorized methods, bots, scripts, or other abuse may result in account restriction or suspension.',
      'accountRestrictionWarning':
          'We may review and restrict accounts that violate network rules. Action depends on the violation.',
      'deviceAlreadyRegistered':
          'This device is already linked to another account.',
      'oneDeviceRuleMessage':
          'One person can use one account on one device. Multiple accounts on the same device are not allowed.',
      'boostCompleted':
          'Boost completed successfully.',
      'dailyBoostCompleted':
          "Today's boost has been completed.",
    },

    // PART 1 continues with the remaining
    // translations in PART 2.
    // PART 2/2
// Ci gaba daga ƙarshen PART 1.

// A nan ne translations na sauran languages suke ci gaba.
// Kada ka ƙara wani class ko wani { a sama.
// Ci gaba da code ɗin kai tsaye daga inda PART 1 ya tsaya.

    'zh': {
      'appName': 'POWER FAN',
      'brandName': 'POWER FAN',
      'mineFan': '挖矿 FAN',
      'powerFanNetwork': 'POWER FAN NETWORK',
      'fan': 'FAN',
      'afam': 'AFAM',
      'language': '语言',
      'selectLanguage': '选择语言',
      'chooseLanguage': '选择您的语言',
      'languageChanged': '语言更改成功',
      'login': '登录',
      'register': '注册',
      'signIn': '登录',
      'signUp': '注册',
      'welcomeBack': '欢迎回来',
      'createAccount': '创建账户',
      'loginToContinue': '登录以继续',
      'joinPowerFanNetwork': '加入 POWER FAN NETWORK',
      'username': '用户名',
      'email': '电子邮件',
      'password': '密码',
      'confirmPassword': '确认密码',
      'referralCode': '推荐码',
      'referralCodeOptional': '推荐码（可选）',
      'enterUsername': '输入用户名',
      'enterEmail': '输入电子邮件',
      'enterPassword': '输入密码',
      'enterReferralCode': '输入推荐码',
      'forgotPassword': '忘记密码？',
      'resetPassword': '重置密码',
      'dontHaveAccount': '还没有账户？',
      'alreadyHaveAccount': '已有账户？',
      'home': '首页',
      'balance': '余额',
      'fanBalance': 'FAN 余额',
      'afamBalance': 'AFAM 余额',
      'miningBalance': '挖矿余额',
      'originalCoin': '原始币',
      'mining': '挖矿',
      'startMining': '开始挖矿',
      'miningNow': '正在挖矿',
      'miningStopped': '挖矿已停止',
      'claimMining': '领取挖矿奖励',
      'claim': '领取',
      'claimed': '已领取',
      'miningRate': '挖矿速度',
      'fanPerHour': 'FAN / 小时',
      'remainingTime': '剩余时间',
      'miningSession': '挖矿会话',
      'boostMining': '提升挖矿',
      'boost': '提升',
      'watchAd': '观看广告',
      'adsWatched': '已观看广告',
      'dailyAds': '每日广告',
      'maxAds': '最大广告数',
      'boostPerAd': '每个广告 +0.1 FAN/H',
      'maximumBoost': '最大提升：+0.7 FAN/H',
      'dailySocialTask': '每日社交任务',
      'socialTasks': '社交任务',
      'dailyTasks': '每日任务',
      'completeTask': '完成任务',
      'openTask': '打开任务',
      'verifyTask': '验证任务',
      'claimReward': '领取奖励',
      'taskCompleted': '任务已完成',
      'taskClaimed': '奖励已领取',
      'taskNotReady': '请先完成必要操作',
      'follow': '关注',
      'comment': '评论',
      'share': '分享',
      'dailyCheckIn': '每日签到',
      'socialReward': '社交奖励',
      'fanReward': 'FAN 奖励',
      'facebook': 'Facebook',
      'instagram': 'Instagram',
      'telegram': 'Telegram',
      'tiktok': 'TikTok',
      'twitterX': 'X',
      'youtube': 'YouTube',
      'referral': '推荐',
      'referrals': '推荐人数',
      'inviteFriends': '邀请朋友',
      'inviteAndEarn': '邀请并赚取',
      'myReferralCode': '我的推荐码',
      'copyCode': '复制代码',
      'shareCode': '分享代码',
      'copied': '已复制',
      'totalReferrals': '总推荐人数',
      'activeReferrals': '活跃推荐人数',
      'referralEarnings': '推荐收益',
      'referralReward': '推荐奖励',
      'newUserReward': '新用户获得 20 FAN',
      'miningBonus': '挖矿奖励',
      'perActiveReferral': '每个活跃推荐 +0.02 FAN/H',
      'wallet': '钱包',
      'afamWallet': 'AFAM 钱包',
      'fanMiningBalance': 'FAN 挖矿余额',
      'migration': '迁移',
      'migrate': '迁移',
      'migrationComingSoon': '迁移即将推出',
      'migrationInfo': '您的 FAN 余额以后可以迁移到 AFAM。',
      'migrationRate': '迁移比例',
      'oneHundredFanOneAfam': '100 FAN = 1 AFAM',
      'transactions': '交易',
      'noTransactions': '暂无交易',
      'send': '发送',
      'receive': '接收',
      'sendAfam': '发送 AFAM',
      'receiveAfam': '接收 AFAM',
      'usernameTransactions': '交易通过用户名进行。',
      'walletSecurity': '钱包安全',
      'kyc': 'KYC',
      'kycVerification': 'KYC 验证',
      'faceVerification': '人脸验证',
      'faceVerificationComingSoon': '人脸验证即将推出',
      'kycComingSoon': 'KYC 即将推出',
      'kycRequirements': 'KYC 要求',
      'kycRequirementOne': '连续完成 30 天每日签到。',
      'kycRequirementTwo': '连续 30 天每天至少完成一次 Boost。',
      'kycRequirementThree': '之后完成 Face Verification。',
      'thirtyDayCheckIn': '30 天每日签到',
      'thirtyDayBoost': '30 天每日 Boost',
      'kycUnlocked': 'KYC 已解锁',
      'kycLocked': 'KYC 已锁定',
      'startFaceVerification': '开始人脸验证',
      'verificationInProgress': '验证进行中',
      'verificationComplete': '验证完成',
      'keepFaceVisible': '请保持脸部在摄像头范围内。',
      'lookAtCamera': '请直视摄像头。',
      'verificationSeconds': '30 秒验证',
      'secondsRemaining': '秒剩余',
      'cameraPermissionRequired': '需要摄像头权限',
      'cameraPermissionMessage': '实时人脸验证需要摄像头访问权限。',
      'oneDeviceOneAccount': '一台设备 = 一个账户',
      'deviceSecurity': '设备安全',
      'settings': '设置',
      'account': '账户',
      'profile': '个人资料',
      'notifications': '通知',
      'security': '安全',
      'privacy': '隐私',
      'about': '关于',
      'help': '帮助',
      'logout': '退出登录',
      'logoutConfirm': '确定要退出登录吗？',
      'save': '保存',
      'cancel': '取消',
      'close': '关闭',
      'continue': '继续',
      'done': '完成',
      'refresh': '刷新',
      'retry': '重试',
      'loading': '加载中...',
      'error': '错误',
      'success': '成功',
      'failed': '失败',
      'comingSoon': '即将推出',
      'enabled': '已启用',
      'disabled': '已禁用',
      'yes': '是',
      'no': '否',
      'today': '今天',
      'tomorrow': '明天',
      'loginRequired': '请先登录。',
      'invalidEmail': '请输入有效的电子邮件地址。',
      'invalidPassword': '密码至少需要 6 个字符。',
      'invalidUsername': '请输入有效的用户名。',
      'passwordsDoNotMatch': '密码不匹配。',
      'somethingWentWrong': '发生了一些错误。',
      'networkError': '网络错误，请重试。',
      'noInternet': '没有互联网连接。',
      'operationSuccessful': '操作成功。',
      'dailyBoostRequired': '需要每日 Boost',
      'robotWarning': '不允许使用机器人或自动化活动。',
      'deviceAlreadyRegistered': '此设备已经与其他账户关联。',
      'oneDeviceRuleMessage': '一个人只能在一台设备上使用一个账户。同一设备不允许多个账户。',
      'boostCompleted': 'Boost 成功完成。',
      'dailyBoostCompleted': '今日 Boost 已完成。',
    },

    'es': {
      'appName': 'POWER FAN',
      'brandName': 'POWER FAN',
      'mineFan': 'Minar FAN',
      'powerFanNetwork': 'POWER FAN NETWORK',
      'fan': 'FAN',
      'afam': 'AFAM',
      'language': 'Idioma',
      'selectLanguage': 'Seleccionar idioma',
      'chooseLanguage': 'Elige tu idioma',
      'languageChanged': 'Idioma cambiado correctamente',
      'login': 'Iniciar sesión',
      'register': 'Registrarse',
      'signIn': 'Iniciar sesión',
      'signUp': 'Crear cuenta',
      'welcomeBack': 'Bienvenido de nuevo',
      'createAccount': 'Crear cuenta',
      'loginToContinue': 'Inicia sesión para continuar',
      'joinPowerFanNetwork': 'Únete a POWER FAN NETWORK',
      'username': 'Nombre de usuario',
      'email': 'Correo electrónico',
      'password': 'Contraseña',
      'confirmPassword': 'Confirmar contraseña',
      'referralCode': 'Código de referido',
      'referralCodeOptional': 'Código de referido (opcional)',
      'enterUsername': 'Introduce tu nombre de usuario',
      'enterEmail': 'Introduce tu correo electrónico',
      'enterPassword': 'Introduce tu contraseña',
      'enterReferralCode': 'Introduce el código de referido',
      'forgotPassword': '¿Olvidaste tu contraseña?',
      'resetPassword': 'Restablecer contraseña',
      'dontHaveAccount': '¿No tienes una cuenta?',
      'alreadyHaveAccount': '¿Ya tienes una cuenta?',
      'home': 'Inicio',
      'balance': 'Saldo',
      'fanBalance': 'Saldo FAN',
      'afamBalance': 'Saldo AFAM',
      'miningBalance': 'Saldo de minería',
      'originalCoin': 'Moneda original',
      'mining': 'Minería',
      'startMining': 'INICIAR MINERÍA',
      'miningNow': 'MINERÍA ACTIVA',
      'miningStopped': 'Minería detenida',
      'claimMining': 'RECLAMAR RECOMPENSA',
      'claim': 'Reclamar',
      'claimed': 'Reclamado',
      'miningRate': 'Tasa de minería',
      'fanPerHour': 'FAN / Hora',
      'remainingTime': 'Tiempo restante',
      'miningSession': 'Sesión de minería',
      'boostMining': 'Aumentar minería',
      'boost': 'Aumentar',
      'watchAd': 'VER ANUNCIO',
      'adsWatched': 'Anuncios vistos',
      'dailyAds': 'Anuncios diarios',
      'maxAds': 'Máximo de anuncios',
      'boostPerAd': '+0.1 FAN/H por anuncio',
      'maximumBoost': 'Aumento máximo: +0.7 FAN/H',
      'dailySocialTask': 'Tarea social diaria',
      'socialTasks': 'Tareas sociales',
      'dailyTasks': 'Tareas diarias',
      'completeTask': 'Completar tarea',
      'openTask': 'ABRIR TAREA',
      'verifyTask': 'VERIFICAR TAREA',
      'claimReward': 'RECLAMAR RECOMPENSA',
      'taskCompleted': 'Tarea completada',
      'taskClaimed': 'Recompensa ya reclamada',
      'taskNotReady': 'Completa primero las acciones requeridas',
      'follow': 'Seguir',
      'comment': 'Comentar',
      'share': 'Compartir',
      'dailyCheckIn': 'Check-in diario',
      'socialReward': 'Recompensa social',
      'fanReward': 'Recompensa FAN',
      'facebook': 'Facebook',
      'instagram': 'Instagram',
      'telegram': 'Telegram',
      'tiktok': 'TikTok',
      'twitterX': 'X',
      'youtube': 'YouTube',
      'referral': 'Referido',
      'referrals': 'Referidos',
      'inviteFriends': 'Invitar amigos',
      'inviteAndEarn': 'Invita y gana',
      'myReferralCode': 'Mi código de referido',
      'copyCode': 'COPIAR CÓDIGO',
      'shareCode': 'COMPARTIR CÓDIGO',
      'copied': 'Copiado',
      'totalReferrals': 'Total de referidos',
      'activeReferrals': 'Referidos activos',
      'referralEarnings': 'Ganancias por referidos',
      'referralReward': 'Recompensa por referido',
      'newUserReward': 'El nuevo usuario recibe 20 FAN',
      'miningBonus': 'Bono de minería',
      'perActiveReferral': '+0.02 FAN/H por referido activo',
      'wallet': 'Billetera',
      'afamWallet': 'Billetera AFAM',
      'fanMiningBalance': 'Saldo de minería FAN',
      'migration': 'Migración',
      'migrate': 'MIGRAR',
      'migrationComingSoon': 'Migración próximamente',
      'migrationInfo': 'Tu saldo FAN podrá migrarse a AFAM más adelante.',
      'migrationRate': 'Tasa de migración',
      'oneHundredFanOneAfam': '100 FAN = 1 AFAM',
      'transactions': 'Transacciones',
      'noTransactions': 'No hay transacciones todavía',
      'send': 'ENVIAR',
      'receive': 'RECIBIR',
      'sendAfam': 'Enviar AFAM',
      'receiveAfam': 'Recibir AFAM',
      'usernameTransactions': 'Las transacciones se realizan mediante el nombre de usuario.',
      'walletSecurity': 'Seguridad de la billetera',
      'kyc': 'KYC',
      'kycVerification': 'Verificación KYC',
      'faceVerification': 'Verificación facial',
      'faceVerificationComingSoon': 'Verificación facial próximamente',
      'kycComingSoon': 'KYC próximamente',
      'kycRequirements': 'Requisitos KYC',
      'kycRequirementOne': 'Completa el check-in diario durante 30 días consecutivos.',
      'kycRequirementTwo': 'Completa al menos un boost cada día durante 30 días.',
      'kycRequirementThree': 'Después completa la verificación facial.',
      'thirtyDayCheckIn': '30 días de check-in diario',
      'thirtyDayBoost': '30 días de boost diario',
      'kycUnlocked': 'KYC desbloqueado',
      'kycLocked': 'KYC bloqueado',
      'startFaceVerification': 'INICIAR VERIFICACIÓN FACIAL',
      'verificationInProgress': 'Verificación en progreso',
      'verificationComplete': 'Verificación completada',
      'keepFaceVisible': 'Mantén tu rostro visible en la cámara.',
      'lookAtCamera': 'Mira directamente a la cámara.',
      'verificationSeconds': 'Verificación de 30 segundos',
      'secondsRemaining': 'segundos restantes',
      'cameraPermissionRequired': 'Se requiere permiso de cámara',
      'cameraPermissionMessage': 'Se necesita acceso a la cámara para la verificación facial en vivo.',
      'oneDeviceOneAccount': 'Un dispositivo = Una cuenta',
      'deviceSecurity': 'Seguridad del dispositivo',
      'settings': 'Configuración',
      'account': 'Cuenta',
      'profile': 'Perfil',
      'notifications': 'Notificaciones',
      'security': 'Seguridad',
      'privacy': 'Privacidad',
      'about': 'Acerca de',
      'help': 'Ayuda',
      'logout': 'Cerrar sesión',
      'logoutConfirm': '¿Quieres cerrar sesión?',
      'save': 'Guardar',
      'cancel': 'Cancelar',
      'close': 'Cerrar',
      'continue': 'Continuar',
      'done': 'Listo',
      'refresh': 'Actualizar',
      'retry': 'Reintentar',
      'loading': 'Cargando...',
      'error': 'Error',
      'success': 'Éxito',
      'failed': 'Fallido',
      'comingSoon': 'Próximamente',
      'enabled': 'Activado',
      'disabled': 'Desactivado',
      'yes': 'Sí',
      'no': 'No',
      'today': 'Hoy',
      'tomorrow': 'Mañana',
      'loginRequired': 'Inicia sesión primero.',
      'invalidEmail': 'Introduce un correo electrónico válido.',
      'invalidPassword': 'La contraseña debe tener al menos 6 caracteres.',
      'invalidUsername': 'Introduce un nombre de usuario válido.',
      'passwordsDoNotMatch': 'Las contraseñas no coinciden.',
      'somethingWentWrong': 'Algo salió mal.',
      'networkError': 'Error de red. Inténtalo de nuevo.',
      'noInternet': 'No hay conexión a Internet.',
      'operationSuccessful': 'Operación exitosa.',
      'dailyBoostRequired': 'Se requiere boost diario',
      'robotWarning': 'No se permiten robots ni actividad automatizada.',
      'deviceAlreadyRegistered': 'Este dispositivo ya está vinculado a otra cuenta.',
      'oneDeviceRuleMessage': 'Una persona puede usar una cuenta en un dispositivo. No se permiten varias cuentas en el mismo dispositivo.',
      'boostCompleted': 'Boost completado correctamente.',
      'dailyBoostCompleted': 'El boost de hoy ya está completado.',
    },

    'fr': {
      'appName': 'POWER FAN',
      'brandName': 'POWER FAN',
      'mineFan': 'Miner du FAN',
      'powerFanNetwork': 'POWER FAN NETWORK',
      'fan': 'FAN',
      'afam': 'AFAM',
      'language': 'Langue',
      'selectLanguage': 'Sélectionner la langue',
      'chooseLanguage': 'Choisissez votre langue',
      'languageChanged': 'Langue modifiée avec succès',
      'login': 'Connexion',
      'register': 'Inscription',
      'signIn': 'Se connecter',
      'signUp': 'Créer un compte',
      'welcomeBack': 'Bon retour',
      'createAccount': 'Créer un compte',
      'loginToContinue': 'Connectez-vous pour continuer',
      'joinPowerFanNetwork': 'Rejoindre POWER FAN NETWORK',
      'username': "Nom d'utilisateur",
      'email': 'E-mail',
      'password': 'Mot de passe',
      'confirmPassword': 'Confirmer le mot de passe',
      'referralCode': 'Code de parrainage',
      'referralCodeOptional': 'Code de parrainage (facultatif)',
      'enterUsername': "Entrez votre nom d'utilisateur",
      'enterEmail': 'Entrez votre e-mail',
      'enterPassword': 'Entrez votre mot de passe',
      'enterReferralCode': 'Entrez le code de parrainage',
      'forgotPassword': 'Mot de passe oublié ?',
      'resetPassword': 'Réinitialiser le mot de passe',
      'dontHaveAccount': "Vous n'avez pas de compte ?",
      'alreadyHaveAccount': 'Vous avez déjà un compte ?',
      'home': 'Accueil',
      'balance': 'Solde',
      'fanBalance': 'Solde FAN',
      'afamBalance': 'Solde AFAM',
      'miningBalance': 'Solde de minage',
      'originalCoin': 'Pièce originale',
      'mining': 'Minage',
      'startMining': 'COMMENCER LE MINAGE',
      'miningNow': 'MINAGE EN COURS',
      'miningStopped': 'Minage arrêté',
      'claimMining': 'RÉCLAMER LA RÉCOMPENSE',
      'claim': 'Réclamer',
      'claimed': 'Réclamé',
      'miningRate': 'Taux de minage',
      'fanPerHour': 'FAN / Heure',
      'remainingTime': 'Temps restant',
      'miningSession': 'Session de minage',
      'boostMining': 'Booster le minage',
      'boost': 'Boost',
      'watchAd': 'REGARDER LA PUBLICITÉ',
      'adsWatched': 'Publicités regardées',
      'dailyAds': 'Publicités quotidiennes',
      'maxAds': 'Publicités maximum',
      'boostPerAd': '+0.1 FAN/H par publicité',
      'maximumBoost': 'Boost maximum : +0.7 FAN/H',
      'dailySocialTask': 'Tâche sociale quotidienne',
      'socialTasks': 'Tâches sociales',
      'dailyTasks': 'Tâches quotidiennes',
      'completeTask': 'Terminer la tâche',
      'openTask': 'OUVRIR LA TÂCHE',
      'verifyTask': 'VÉRIFIER LA TÂCHE',
      'claimReward': 'RÉCLAMER LA RÉCOMPENSE',
      'taskCompleted': 'Tâche terminée',
      'taskClaimed': 'Récompense déjà réclamée',
      'taskNotReady': "Terminez d'abord les actions requises",
      'follow': 'Suivre',
      'comment': 'Commenter',
      'share': 'Partager',
      'dailyCheckIn': 'Check-in quotidien',
      'socialReward': 'Récompense sociale',
      'fanReward': 'Récompense FAN',
      'facebook': 'Facebook',
      'instagram': 'Instagram',
      'telegram': 'Telegram',
      'tiktok': 'TikTok',
      'twitterX': 'X',
      'youtube': 'YouTube',
      'referral': 'Parrainage',
      'referrals': 'Parrainages',
      'inviteFriends': 'Inviter des amis',
      'inviteAndEarn': 'Invitez et gagnez',
      'myReferralCode': 'Mon code de parrainage',
      'copyCode': 'COPIER LE CODE',
      'shareCode': 'PARTAGER LE CODE',
      'copied': 'Copié',
      'totalReferrals': 'Total des parrainages',
      'activeReferrals': 'Parrainages actifs',
      'referralEarnings': 'Gains de parrainage',
      'referralReward': 'Récompense de parrainage',
      'newUserReward': 'Le nouvel utilisateur reçoit 20 FAN',
      'miningBonus': 'Bonus de minage',
      'perActiveReferral': '+0.02 FAN/H par parrainage actif',
      'wallet': 'Portefeuille',
      'afamWallet': 'Portefeuille AFAM',
      'fanMiningBalance': 'Solde de minage FAN',
      'migration': 'Migration',
      'migrate': 'MIGRER',
      'migrationComingSoon': 'Migration bientôt disponible',
      'migrationInfo': 'Votre solde FAN pourra être migré vers AFAM ultérieurement.',
      'migrationRate': 'Taux de migration',
      'oneHundredFanOneAfam': '100 FAN = 1 AFAM',
      'transactions': 'Transactions',
      'noTransactions': 'Aucune transaction pour le moment',
      'send': 'ENVOYER',
      'receive': 'RECEVOIR',
      'sendAfam': 'Envoyer AFAM',
      'receiveAfam': 'Recevoir AFAM',
      'usernameTransactions': "Les transactions sont effectuées via le nom d'utilisateur.",
      'walletSecurity': 'Sécurité du portefeuille',
      'kyc': 'KYC',
      'kycVerification': 'Vérification KYC',
      'faceVerification': 'Vérification faciale',
      'faceVerificationComingSoon': 'Vérification faciale bientôt disponible',
      'kycComingSoon': 'KYC bientôt disponible',
      'kycRequirements': 'Exigences KYC',
      'kycRequirementOne': 'Effectuez le check-in quotidien pendant 30 jours consécutifs.',
      'kycRequirementTwo': 'Effectuez au moins un boost chaque jour pendant 30 jours.',
      'kycRequirementThree': 'Ensuite, terminez la vérification faciale.',
      'thirtyDayCheckIn': '30 jours de check-in quotidien',
      'thirtyDayBoost': '30 jours de boost quotidien',
      'kycUnlocked': 'KYC déverrouillé',
      'kycLocked': 'KYC verrouillé',
      'startFaceVerification': 'COMMENCER LA VÉRIFICATION FACIALE',
      'verificationInProgress': 'Vérification en cours',
      'verificationComplete': 'Vérification terminée',
      'keepFaceVisible': 'Gardez votre visage visible dans la caméra.',
      'lookAtCamera': 'Regardez directement la caméra.',
      'verificationSeconds': 'Vérification de 30 secondes',
      'secondsRemaining': 'secondes restantes',
      'cameraPermissionRequired': 'Autorisation de caméra requise',
      'cameraPermissionMessage': "L'accès à la caméra est nécessaire pour la vérification faciale en direct.",
      'oneDeviceOneAccount': 'Un appareil = Un compte',
      'deviceSecurity': 'Sécurité de l’appareil',
      'settings': 'Paramètres',
      'account': 'Compte',
      'profile': 'Profil',
      'notifications': 'Notifications',
      'security': 'Sécurité',
      'privacy': 'Confidentialité',
      'about': 'À propos',
      'help': 'Aide',
      'logout': 'Se déconnecter',
      'logoutConfirm': 'Voulez-vous vous déconnecter ?',
      'save': 'Enregistrer',
      'cancel': 'Annuler',
      'close': 'Fermer',
      'continue': 'Continuer',
      'done': 'Terminé',
      'refresh': 'Actualiser',
      'retry': 'Réessayer',
      'loading': 'Chargement...',
      'error': 'Erreur',
      'success': 'Succès',
      'failed': 'Échec',
      'comingSoon': 'Bientôt disponible',
      'enabled': 'Activé',
      'disabled': 'Désactivé',
      'yes': 'Oui',
      'no': 'Non',
      'today': "Aujourd'hui",
      'tomorrow': 'Demain',
      'loginRequired': 'Veuillez vous connecter d’abord.',
      'invalidEmail': 'Entrez une adresse e-mail valide.',
      'invalidPassword': 'Le mot de passe doit contenir au moins 6 caractères.',
      'invalidUsername': "Entrez un nom d'utilisateur valide.",
      'passwordsDoNotMatch': 'Les mots de passe ne correspondent pas.',
      'somethingWentWrong': "Une erreur s'est produite.",
      'networkError': 'Erreur réseau. Réessayez.',
      'noInternet': 'Pas de connexion Internet.',
      'operationSuccessful': 'Opération réussie.',
      'dailyBoostRequired': 'Boost quotidien requis',
      'robotWarning': 'Les robots et activités automatisées ne sont pas autorisés.',
      'deviceAlreadyRegistered': 'Cet appareil est déjà lié à un autre compte.',
      'oneDeviceRuleMessage': 'Une personne peut utiliser un compte sur un appareil. Plusieurs comptes sur le même appareil ne sont pas autorisés.',
      'boostCompleted': 'Boost terminé avec succès.',
      'dailyBoostCompleted': "Le boost d'aujourd'hui est terminé.",
    },
